name:                servant-perf
version:             0.1.0.0
github:              "ford-prefect/servant-perf"
license:             BSD3
author:              "Arun Raghavan"
maintainer:          "arun@arunraghavan.net"
copyright:           "2020 Arun Raghavan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ford-prefect/servant-perf#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- text
- wai
- warp

library:
  source-dirs: src

executables:
  servant-perf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-perf

tests:
  servant-perf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-perf
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
